import type { PropsWithChildren } from "react";

const proseClasses = [
    "text-brand-black text-base leading-7",
    "[&>:first-child]:mt-0",
    "[&_p]:mt-5 [&_p]:text-pretty",
    "[&_strong]:font-semibold",
    "[&_em]:italic",
    "[&_del]:text-brand-gray [&_del]:line-through",
    "[&_a]:text-brand-primary [&_a]:break-words [&_a]:underline",
    "[&_a]:decoration-1 [&_a]:underline-offset-[3px]",
    "[&_a:hover]:text-brand-primaryHover [&_a:hover]:decoration-2",
    "[&_h1]:mt-12 [&_h1]:text-3xl [&_h1]:font-bold [&_h1]:tracking-tight",
    "[&_h2]:border-brand-border [&_h2]:mt-12 [&_h2]:border-t [&_h2]:pt-8",
    "[&_h2]:text-2xl [&_h2]:font-semibold [&_h2]:tracking-tight",
    "[&>h2:first-child]:border-t-0 [&>h2:first-child]:pt-0",
    "[&_h3]:mt-8 [&_h3]:text-lg [&_h3]:leading-snug [&_h3]:font-semibold",
    "[&_h4]:mt-6 [&_h4]:text-base [&_h4]:font-semibold",
    "[&_h5]:mt-6 [&_h5]:text-base [&_h5]:font-semibold",
    "[&_h6]:text-brand-gray [&_h6]:mt-6 [&_h6]:text-sm [&_h6]:font-semibold",
    "[&_h6]:tracking-[0.08em] [&_h6]:uppercase",
    "[&_h2+h3]:mt-5 [&_h3+h4]:mt-3 [&_h4+h5]:mt-3 [&_h5+h6]:mt-3",
    "[&_h1+p]:mt-4 [&_h2+p]:mt-4 [&_h3+p]:mt-2 [&_h4+p]:mt-2",
    "[&_h5+p]:mt-2 [&_h6+p]:mt-2",
    "[&_h2+ul]:mt-4 [&_h3+ul]:mt-2 [&_h4+ul]:mt-2",
    "[&_h2+ol]:mt-4 [&_h3+ol]:mt-2 [&_h4+ol]:mt-2",
    "[&_p+ul]:mt-3 [&_p+ol]:mt-3",
    "[&_ul]:mt-5 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:marker:text-brand-gray",
    "[&_ol]:mt-5 [&_ol]:list-decimal [&_ol]:pl-5 [&_ol]:marker:text-brand-gray",
    "[&_li]:mt-1.5 [&_li]:pl-1",
    "[&_li>ul]:mt-1.5 [&_li>ol]:mt-1.5",
    "[&_li_p]:mt-3 [&_li>p:first-of-type]:mt-0",
    "[&_[data-task-list]]:list-none [&_[data-task-list]]:pl-0",
    "[&_li_[data-task-list]]:pl-6",
    "[&_[data-task-item]]:pl-0",
    "[&_[data-task-item]>input]:accent-brand-primary",
    "[&_[data-task-item]>input]:mr-1.5 [&_[data-task-item]>input]:align-middle",
    "[&_[data-task-item]>p:first-of-type]:inline",
    "[&_blockquote]:border-brand-primary [&_blockquote]:text-brand-gray",
    "[&_blockquote]:mt-6 [&_blockquote]:border-l-2 [&_blockquote]:pl-5",
    "[&_blockquote_blockquote]:mt-4",
    "[&_blockquote>p:first-child]:mt-0",
    "[&_code]:bg-brand-surface [&_code]:rounded-md [&_code]:px-1.5",
    "[&_code]:py-0.5 [&_code]:font-mono [&_code]:text-[0.875em]",
    "[&_pre]:border-brand-border [&_pre]:bg-brand-surface [&_pre]:mt-6",
    "[&_pre]:overflow-x-auto [&_pre]:rounded-md [&_pre]:border [&_pre]:p-4",
    "[&_pre]:text-sm [&_pre]:leading-6",
    "[&_pre_code]:bg-transparent [&_pre_code]:p-0 [&_pre_code]:text-[1em]",
    "[&_hr]:border-brand-border [&_hr]:mt-12 [&_hr+*]:mt-12",
    "[&_img]:rounded-md",
    "[&_sup]:text-xs [&_sup_a]:no-underline [&_sup_a]:font-medium",
    "[&_[data-table-scroll]]:mt-6 [&_[data-table-scroll]]:overflow-x-auto",
    "[&_table]:w-full [&_table]:text-sm [&_table]:leading-6",
    "[&_th]:border-brand-black [&_th]:border-b [&_th]:px-3 [&_th]:py-2",
    "[&_th]:text-left [&_th]:font-semibold [&_th]:align-bottom",
    "[&_td]:border-brand-border [&_td]:border-b [&_td]:px-3 [&_td]:py-2",
    "[&_td]:align-top",
    "[&_th:first-child]:pl-0 [&_td:first-child]:pl-0",
    "[&_th:last-child]:pr-0 [&_td:last-child]:pr-0",
    "[&_[data-align=left]]:text-left",
    "[&_[data-align=center]]:text-center",
    "[&_[data-align=right]]:text-right",
    "[&_[data-footnotes]]:border-brand-border [&_[data-footnotes]]:text-brand-gray",
    "[&_[data-footnotes]]:mt-12 [&_[data-footnotes]]:border-t",
    "[&_[data-footnotes]]:pt-6 [&_[data-footnotes]]:text-sm",
    "[&_[data-footnotes]]:leading-6",
    "[&_[data-footnotes]_h2]:text-brand-gray [&_[data-footnotes]_h2]:mt-0",
    "[&_[data-footnotes]_h2]:border-t-0 [&_[data-footnotes]_h2]:pt-0",
    "[&_[data-footnotes]_h2]:text-xs [&_[data-footnotes]_h2]:font-semibold",
    "[&_[data-footnotes]_h2]:tracking-[0.08em] [&_[data-footnotes]_h2]:uppercase",
    "[&_[data-footnotes]_ol]:mt-3 [&_[data-footnotes]_p]:mt-2",
].join(" ");

const Prose = ({ children }: PropsWithChildren) => (
    <div className={proseClasses}>{children}</div>
);

export default Prose;
