import type { PropsWithChildren } from "react";
import classNames from "../classNames";

const proseClasses = [
    "text-brand-text text-base leading-7",
    "[&>:first-child]:mt-0",
    "[:where(&)_p]:mt-5 [:where(&)_p]:text-pretty",
    "[:where(&)_strong]:font-semibold",
    "[:where(&)_em]:italic",
    "[:where(&)_del]:text-brand-muted [:where(&)_del]:line-through",
    "[:where(&)_a]:text-brand-primary [:where(&)_a]:break-words",
    "[:where(&)_a]:underline [:where(&)_a]:decoration-1",
    "[:where(&)_a]:underline-offset-[3px]",
    "[:where(&)_a:hover]:text-brand-primaryHover [:where(&)_a:hover]:decoration-2",
    "[:where(&)_h1]:mt-12 [:where(&)_h1]:text-3xl [:where(&)_h1]:font-bold",
    "[:where(&)_h1]:tracking-tight",
    "[:where(&)_h2]:border-brand-border [:where(&)_h2]:mt-12",
    "[:where(&)_h2]:border-t [:where(&)_h2]:pt-8 [:where(&)_h2]:text-2xl",
    "[:where(&)_h2]:font-semibold [:where(&)_h2]:tracking-tight",
    "[:where(&)>h2:first-child]:border-t-0 [:where(&)>h2:first-child]:pt-0",
    "[:where(&)_h3]:mt-8 [:where(&)_h3]:text-lg [:where(&)_h3]:leading-snug",
    "[:where(&)_h3]:font-semibold",
    "[:where(&)_h4]:mt-6 [:where(&)_h4]:text-base [:where(&)_h4]:font-semibold",
    "[:where(&)_h5]:mt-6 [:where(&)_h5]:text-base [:where(&)_h5]:font-semibold",
    "[:where(&)_h6]:text-brand-muted [:where(&)_h6]:mt-6 [:where(&)_h6]:text-sm",
    "[:where(&)_h6]:font-semibold [:where(&)_h6]:tracking-[0.08em]",
    "[:where(&)_h6]:uppercase",
    "[:where(&)_h2+h3]:mt-5 [:where(&)_h3+h4]:mt-3 [:where(&)_h4+h5]:mt-3",
    "[:where(&)_h5+h6]:mt-3",
    "[:where(&)_h1+p]:mt-4 [:where(&)_h2+p]:mt-4 [:where(&)_h3+p]:mt-2",
    "[:where(&)_h4+p]:mt-2 [:where(&)_h5+p]:mt-2 [:where(&)_h6+p]:mt-2",
    "[:where(&)_h2+ul]:mt-4 [:where(&)_h3+ul]:mt-2 [:where(&)_h4+ul]:mt-2",
    "[:where(&)_h2+ol]:mt-4 [:where(&)_h3+ol]:mt-2 [:where(&)_h4+ol]:mt-2",
    "[:where(&)_p+ul]:mt-3 [:where(&)_p+ol]:mt-3",
    "[:where(&)_ul]:mt-5 [:where(&)_ul]:list-disc [:where(&)_ul]:pl-5",
    "[:where(&)_ul]:marker:text-brand-muted",
    "[:where(&)_ol]:mt-5 [:where(&)_ol]:list-decimal [:where(&)_ol]:pl-5",
    "[:where(&)_ol]:marker:text-brand-muted",
    "[:where(&)_li]:mt-1.5 [:where(&)_li]:pl-1",
    "[:where(&)_li>ul]:mt-1.5 [:where(&)_li>ol]:mt-1.5",
    "[:where(&)_li_p]:mt-3 [:where(&)_li>p:first-of-type]:mt-0",
    "[:where(&)_[data-task-list]]:list-none [:where(&)_[data-task-list]]:pl-0",
    "[:where(&)_li_[data-task-list]]:pl-6",
    "[:where(&)_[data-task-item]]:pl-0",
    "[:where(&)_[data-task-item]>input]:accent-brand-primary",
    "[:where(&)_[data-task-item]>input]:mr-1.5",
    "[:where(&)_[data-task-item]>input]:align-middle",
    "[:where(&)_[data-task-item]>p:first-of-type]:inline",
    "[:where(&)_blockquote]:border-brand-primary",
    "[:where(&)_blockquote]:text-brand-muted [:where(&)_blockquote]:mt-6",
    "[:where(&)_blockquote]:border-l-2 [:where(&)_blockquote]:pl-5",
    "[:where(&)_blockquote_blockquote]:mt-4",
    "[:where(&)_blockquote>p:first-child]:mt-0",
    "[:where(&)_code]:bg-brand-surface [:where(&)_code]:rounded-md",
    "[:where(&)_code]:px-1.5 [:where(&)_code]:py-0.5 [:where(&)_code]:font-mono",
    "[:where(&)_code]:text-[0.875em]",
    "[:where(&)_pre]:border-brand-border [:where(&)_pre]:bg-brand-surface",
    "[:where(&)_pre]:mt-6 [:where(&)_pre]:overflow-x-auto",
    "[:where(&)_pre]:rounded-md [:where(&)_pre]:border [:where(&)_pre]:p-4",
    "[:where(&)_pre]:text-sm [:where(&)_pre]:leading-6",
    "[:where(&)_pre_code]:bg-transparent [:where(&)_pre_code]:p-0",
    "[:where(&)_pre_code]:text-[1em]",
    "[:where(&)_hr]:border-brand-border [:where(&)_hr]:mt-12",
    "[:where(&)_hr+*]:mt-12",
    "[:where(&)_img]:rounded-md",
    "[:where(&)_sup]:text-xs [:where(&)_sup_a]:no-underline",
    "[:where(&)_sup_a]:font-medium",
    "[:where(&)_[data-table-scroll]]:mt-6",
    "[:where(&)_[data-table-scroll]]:overflow-x-auto",
    "[:where(&)_table]:w-full [:where(&)_table]:text-sm",
    "[:where(&)_table]:leading-6",
    "[:where(&)_th]:border-brand-text [:where(&)_th]:border-b",
    "[:where(&)_th]:px-3 [:where(&)_th]:py-2 [:where(&)_th]:text-left",
    "[:where(&)_th]:font-semibold [:where(&)_th]:align-bottom",
    "[:where(&)_td]:border-brand-border [:where(&)_td]:border-b",
    "[:where(&)_td]:px-3 [:where(&)_td]:py-2 [:where(&)_td]:align-top",
    "[:where(&)_th:first-child]:pl-0 [:where(&)_td:first-child]:pl-0",
    "[:where(&)_th:last-child]:pr-0 [:where(&)_td:last-child]:pr-0",
    "[:where(&)_[data-align=left]]:text-left",
    "[:where(&)_[data-align=center]]:text-center",
    "[:where(&)_[data-align=right]]:text-right",
    "[:where(&)_[data-footnotes]]:border-brand-border",
    "[:where(&)_[data-footnotes]]:text-brand-muted",
    "[:where(&)_[data-footnotes]]:mt-12 [:where(&)_[data-footnotes]]:border-t",
    "[:where(&)_[data-footnotes]]:pt-6 [:where(&)_[data-footnotes]]:text-sm",
    "[:where(&)_[data-footnotes]]:leading-6",
    "[:where(&)_[data-footnotes]_h2]:text-brand-muted",
    "[:where(&)_[data-footnotes]_h2]:mt-0",
    "[:where(&)_[data-footnotes]_h2]:border-t-0",
    "[:where(&)_[data-footnotes]_h2]:pt-0",
    "[:where(&)_[data-footnotes]_h2]:text-xs",
    "[:where(&)_[data-footnotes]_h2]:font-semibold",
    "[:where(&)_[data-footnotes]_h2]:tracking-[0.08em]",
    "[:where(&)_[data-footnotes]_h2]:uppercase",
    "[:where(&)_[data-footnotes]_ol]:mt-3 [:where(&)_[data-footnotes]_p]:mt-2",
].join(" ");

type ProseProps = PropsWithChildren<{
    className?: string;
}>;

const Prose = ({ className, children }: ProseProps) => (
    <div className={classNames(proseClasses, className)}>{children}</div>
);

export default Prose;
