import type { PropsWithChildren } from "react";

const Prose = ({ children }: PropsWithChildren) => (
    <div className="text-brand-black [&_a]:text-brand-primary [&_a:hover]:text-brand-primaryHover [&_blockquote]:border-brand-primary [&_blockquote]:bg-brand-surface [&_code]:bg-brand-surface [&_del]:text-brand-gray [&_h6]:text-brand-gray [&_hr]:border-brand-border [&_pre]:bg-brand-surface [&_td]:border-brand-border [&_th]:border-brand-border [&_th]:bg-brand-surface [&_[data-footnotes]]:border-brand-border [&_[data-footnotes]]:text-brand-gray [&_[data-footnotes]_h2]:text-brand-black text-base leading-relaxed [&_[data-align=center]]:text-center [&_[data-align=left]]:text-left [&_[data-align=right]]:text-right [&_[data-footnotes]]:mt-10 [&_[data-footnotes]]:border-t [&_[data-footnotes]]:pt-6 [&_[data-footnotes]]:text-sm [&_[data-footnotes]_h2]:mt-0 [&_[data-footnotes]_h2]:text-base [&_[data-footnotes]_h2]:font-semibold [&_[data-table-scroll]]:mt-6 [&_[data-table-scroll]]:overflow-x-auto [&_[data-task-item]>input]:align-middle [&_[data-task-item]>p:first-of-type]:inline [&_[data-task-list]]:list-none [&_a]:break-words [&_a]:underline [&_a]:underline-offset-2 [&_blockquote]:mt-6 [&_blockquote]:rounded-md [&_blockquote]:border-l-4 [&_blockquote]:p-4 [&_code]:rounded-md [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:text-sm [&_del]:line-through [&_h1]:mt-10 [&_h1]:text-3xl [&_h1]:font-bold [&_h1]:tracking-tight [&_h2]:mt-10 [&_h2]:text-xl [&_h2]:font-semibold [&_h3]:mt-8 [&_h3]:text-lg [&_h3]:font-semibold [&_h4]:mt-6 [&_h4]:text-base [&_h4]:font-semibold [&_h5]:mt-6 [&_h5]:font-semibold [&_h6]:mt-6 [&_h6]:font-semibold [&_hr]:mt-10 [&_img]:rounded-md [&_li]:mt-2 [&_ol]:mt-4 [&_ol]:list-decimal [&_ol]:pl-6 [&_p]:mt-4 [&_pre]:mt-6 [&_pre]:overflow-x-auto [&_pre]:rounded-md [&_pre]:p-4 [&_pre]:text-sm [&_pre_code]:bg-transparent [&_pre_code]:p-0 [&_strong]:font-semibold [&_table]:text-sm [&_td]:border [&_td]:px-3 [&_td]:py-2 [&_td]:align-top [&_th]:border [&_th]:px-3 [&_th]:py-2 [&_th]:text-left [&_th]:font-semibold [&_ul]:mt-4 [&_ul]:list-disc [&_ul]:pl-6 [&>:first-child]:mt-0">
        {children}
    </div>
);

export default Prose;
